name: eatfud
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15

  country_picker: ^2.0.21
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
