name: eatfud
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  country_picker: ^2.0.21
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.24.2
  firebase_auth_utility: ^0.0.6
  firebase_auth: ^4.16.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  flutter_geofire: ^2.0.3
  geolocator: ^11.0.0
  cloud_firestore: ^4.14.0
  uuid: ^4.2.2
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/categories/
    - assets/images/splashScreenImage/

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
